### ISSUE TITLE
一键安装debian image 文件不存在

### ISSUE THREAD

**Issue by CosmosAtlas** [Aniverse/WiKi#3]
默认的rescue系统里面的debian image已经更新到108，109了，readme里面用的版本已经不存在了。

**Comment by Aniverse** [comment]
这个好久没更新了，我自己也基本弃坑状态……
我很早以前自己就改用 images/Debian-stable-64-minimal.tar.gz 这样的写法了，省得一有新镜像就要改名字。
现在 README 已更新
